version: "3.5"

services:
  nest_postgres:
    container_name: postgres_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - nest_postgres:${PGDATA}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - nest_postgres
    restart: unless-stopped

  nest_pgadmin:
    container_name: pgadmin_container
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - nest_pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - nest_postgres
    restart: unless-stopped

networks:
  nest_postgres:
    driver: bridge

volumes:
  nest_postgres:
  nest_pgadmin:
